
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 10 13:56:32 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 3;
  public static final int IDENT = 26;
  public static final int QUESTION = 25;
  public static final int PLUS = 8;
  public static final int RPAREN = 21;
  public static final int RBRACE = 17;
  public static final int EQUAL = 15;
  public static final int SEMI = 22;
  public static final int NUM_CONST = 29;
  public static final int MINUSMINUS = 14;
  public static final int BOOL_CONST = 27;
  public static final int COLON = 24;
  public static final int LPAREN = 20;
  public static final int LBRACKET = 18;
  public static final int LBRACE = 16;
  public static final int RBRACKET = 19;
  public static final int COMMA = 23;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int PROG = 2;
  public static final int PLUSPLUS = 13;
  public static final int MINUS = 9;
  public static final int CONST = 6;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int PROC = 12;
  public static final int NEW = 5;
  public static final int MUL = 10;
  public static final int VOID = 7;
  public static final int CHAR_CONST = 28;
}

